---
- hosts: vyatta1
  gather_facts: no
  become: false
  connection: local
  vars_files: 
  - vars/vyos_users.yml
  tasks:
  - name: Add Vyatta users
    vyos_user:
      name: "{{ item.name }}"
      configured_password: "{{ item.configured_password }}"
      state: "{{ item.state }}"
      #full_name: "{{ item.fullname }}"
      level: "{{ item.level }}"
#      update_password: "{{ item.update_password }}"
    with_items: "{{ users }}"
  - name: Setup user SSH keys
    vyos_config:
      lines:
        - set system login user "{{ item.name }}" authentication public-keys identifier key "{{ item.key }}"
        - set system login user "{{ item.name }}" authentication public-keys identifier type ssh-rsa
      save: yes
    with_items: "{{ users }}"
  - name: Backup config
    vyos_config:
      backup: yes
