---
- name: Create a Teleport SSH auth server instance
  hosts: localhost
  connection: local
  gather_facts: False
  become: False
  vars:
    key_name: 
    instance_type: t2.micro
    sg: 
    image: 
    region: us-east-1
    instance_name: 
    app: nothing
    backup: true 
    auth_servers: ""
    iam_profile: 
    node_name: "{{ ansible_hostname }}"
    poc: someone
    start_stop: 1
    env: dev

  tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ key_name }}"
         group_id: "{{ sg }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: 
         assign_public_ip: yes
         instance_profile_name: "{{ iam_profile }}"
         instance_tags:
             Application: "{{ app }}"   
             Backup: "{{ backup }}"
             POC: "{{ poc }}"
             Environment: "{{ env }}"
             Name: "{{ instance_name }}"
             Team: "{{ app }}"  
             ec2startstop: "{{ start_stop }}"                
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 300
        state: started
      with_items: "{{ ec2.instances }}"

- name: Configure instance(s)
  hosts: launched
  become: True
  gather_facts: True
  roles:
  - role: teleport 
    vars: 
    - teleport_config: |
        teleport:
          nodename: "{{ node_name }}"
          auth_token: hello
          auth_servers:
          - "{{ auth_servers }}"
          data_dir: /var/lib/teleporter
          log:
            output: syslog
            severity: ERROR
        proxy_service:
          enabled: "no"
        auth_service:
          enabled: "no"
        ssh_service:
          enabled: "yes"
          listen_addr: 0.0.0.0:3022
          permit_user_env: false  

- name: Register instance with AWS System Manager
  hosts: launched
  become: True
  gather_facts: True
  roles:
  - role: aws_ssm

- name: Announce new host deployment
  hosts: rc01
  roles:
   - role: ansible_rc_alert
     vars:
     - instance_name: 
     - region: 
     - message: "Finished deploying {{ instance_name }}"          
