---
- name: Install and configure Teleport SSH service
  hosts: all
  become: true
  gather_facts: true
  strategy: debug  
  vars:
  - auth_servers: ""
  - node_name: "{{ ansible_hostname }}"
  roles:
  - role: teleport 
    vars: 
    - teleport_config: |
        teleport:
          nodename: "{{ node_name }}"
          auth_token: hello
          auth_servers:
          - "{{ auth_servers }}"
          data_dir: /var/lib/teleport
          log: 
            output: syslog
            severity: ERROR
        proxy_service:
          enabled: "no"
        auth_service:
          enabled: "no"
        ssh_service:
          enabled: "yes"
          listen_addr: 0.0.0.0:3022
          permit_user_env: false  