---
- hosts: web
  become: true
  roles:
  - role: parted
    vars:
    - create_label: true
    - label: msdos
    - hdds:
      - /dev/xvdg
    - partitions:
      - {'partition_type':'primary','start_point':'0%','end_point':'100%'}
   
  - role: ansible-manage-lvm
    create_vg: true
    create_lv: true
    fs_manage: true
    fstype_OS: ext4
    profile: apache
    apache:
     - pvname: "/dev/xvdg1"
       vgname: ApacheVG2
       lvs:
       - { lvname: webdata_lv, size: 100%FREE, fstype: "{{ fstype_OS }}", mntpoint: "/data1", user: root, group: root, mode: 770 }
          

  
